import { DiagramKey } from '../shared/diagrams';

/**
 * The interview bank. Two kinds of questions:
 *  - mcq  : one correct choice, auto-graded.
 *  - open : you answer out loud / in the textarea; key points are auto-detected by keywords,
 *           then YOU confirm each one (self-grading, like a real debrief).
 * Explanations are HTML (rendered with [innerHTML]) and may reference a diagram + a lesson.
 */
export type Topic = 'angular' | 'dotnet' | 'auth' | 'architecture';
export type Level = 1 | 2 | 3;

interface Base {
  id: string; topic: Topic; level: Level; question: string;
  explanation?: string;          // MCQ: always set. Open: the `model` answer plays that role.
  diagram?: DiagramKey; lesson?: string;
}
export interface McqQuestion extends Base { type: 'mcq'; choices: string[]; answer: number; }
export interface KeyPoint { text: string; keywords: string[]; }
export interface OpenQuestion extends Base { type: 'open'; keyPoints: KeyPoint[]; model: string; }
export type Question = McqQuestion | OpenQuestion;

export const TOPICS: Record<Topic, { label: string; color: string }> = {
  angular: { label: 'Angular', color: 'var(--angular)' },
  dotnet: { label: '.NET', color: 'var(--dotnet)' },
  auth: { label: 'Auth & sécurité', color: 'var(--auth)' },
  architecture: { label: 'Architecture', color: 'var(--brand-2)' },
};
export const LEVELS: Record<Level, string> = { 1: 'Junior', 2: 'Confirmé', 3: 'Senior' };

export const QUESTIONS: Question[] = [
  // ═══════════════════════════ ANGULAR ═══════════════════════════
  {
    id: 'ng-signals-false', topic: 'angular', level: 1, type: 'mcq',
    question: 'À propos des signals Angular, quelle affirmation est FAUSSE ?',
    choices: [
      'Un computed() est paresseux et mémoïsé : il ne recalcule que si une dépendance a changé et que quelqu’un le lit.',
      'Un effect() s’exécute au moins une fois, puis à chaque changement d’un signal qu’il a lu.',
      'On peut écrire dans un signal à l’intérieur d’un computed() pour synchroniser deux états.',
      'untracked() permet de lire un signal sans créer de dépendance.',
    ],
    answer: 2,
    explanation: `<p>Un <code>computed</code> doit être <strong>pur</strong> : écrire dans un signal depuis un computed est interdit (Angular lève une erreur). Les effets de bord vont dans un <code>effect()</code>, et la synchronisation de deux états se fait avec un <code>computed</code> dérivé ou un <code>linkedSignal</code>.</p>`,
    diagram: 'signals', lesson: 'signals-state',
  },
  {
    id: 'ng-signals-mental', topic: 'angular', level: 2, type: 'open',
    question: 'Explique le modèle mental des signals et pourquoi ils rendent possible un Angular sans zone.js.',
    keyPoints: [
      { text: 'Un signal connaît ses lecteurs : graphe de dépendances', keywords: ['graphe', 'dépendance', 'dependance', 'lecteur', 'consommateur', 'track'] },
      { text: 'computed = dérivé, paresseux, mémoïsé', keywords: ['computed', 'mémo', 'memo', 'paresseux', 'lazy', 'cache'] },
      { text: 'effect = effet de bord (log, storage, DOM), pas de l’état', keywords: ['effect', 'effet de bord', 'side effect'] },
      { text: 'Notification ciblée : seuls les nœuds dépendants sont marqués dirty', keywords: ['dirty', 'ciblé', 'cible', 'précis', 'granul', 'notif'] },
      { text: 'Sans zone.js, Angular ne devine plus : le rendu est déclenché par les signals, les événements du template, async pipe', keywords: ['zone', 'zoneless', 'événement', 'evenement', 'async pipe', 'markforcheck'] },
    ],
    model: `<p>Un signal est une boîte qui contient une valeur et qui <strong>enregistre qui la lit</strong>. Quand on l’écrit, il notifie précisément ses lecteurs : les <code>computed</code> (dérivés, recalculés paresseusement et mis en cache) et les <code>effect</code> (effets de bord). Le template qui lit un signal devient lui aussi un lecteur. Avec zone.js, Angular re-vérifiait <em>tout</em> l’arbre après chaque événement asynchrone parce qu’il ne savait pas ce qui avait changé ; avec les signals il le sait exactement, donc zone.js devient inutile : le rendu est planifié par les signals, les événements du template et l’async pipe.</p>`,
    diagram: 'signals', lesson: 'control-flow',
  },
  {
    id: 'ng-for-track', topic: 'angular', level: 1, type: 'mcq',
    question: 'Pourquoi @for exige-t-il une expression track ?',
    choices: [
      'Pour typer les éléments de la liste.',
      'Pour donner une identité stable à chaque élément afin de réutiliser le DOM au lieu de le recréer quand la liste change.',
      'Pour activer le lazy loading des lignes.',
      'C’est optionnel, c’est juste une convention de lint.',
    ],
    answer: 1,
    explanation: `<p>Sans identité, Angular ne peut pas savoir si « l’élément 3 » est le même qu’avant : il détruit et recrée le DOM (et perd le focus, l’état des inputs, les animations). Avec <code>track item.id</code>, il déplace/réutilise les nœuds. <code>track $index</code> est acceptable pour des listes statiques ; <code>track item</code> (l’objet) ne marche que si les références sont stables.</p>`,
    lesson: 'control-flow',
  },
  {
    id: 'ng-rxjs-vs-signals', topic: 'angular', level: 2, type: 'open',
    question: 'Quand utilises-tu RxJS plutôt que des signals, et comment les fais-tu cohabiter ?',
    keyPoints: [
      { text: 'Signals = état synchrone et dérivations', keywords: ['état', 'etat', 'synchrone', 'dériv', 'deriv'] },
      { text: 'RxJS = flux d’événements dans le temps : debounce, switchMap, retry, annulation', keywords: ['temps', 'flux', 'debounce', 'switchmap', 'retry', 'annul', 'cancel', 'websocket'] },
      { text: 'Interop : toSignal / toObservable', keywords: ['tosignal', 'toobservable', 'interop'] },
      { text: 'httpResource / resource pour un GET dépendant d’un signal', keywords: ['httpresource', 'resource'] },
    ],
    model: `<p>Les signals gèrent <strong>l’état</strong> : une valeur à un instant T et ce qui en dérive. RxJS gère <strong>le temps</strong> : une frappe clavier qu’il faut debouncer, une requête qu’il faut annuler quand une nouvelle arrive (<code>switchMap</code>), un WebSocket, un retry avec backoff. Le pattern gagnant : RxJS pour orchestrer l’événement, puis <code>toSignal()</code> pour exposer le résultat au template. Pour un simple GET qui dépend d’un signal, <code>httpResource</code> évite même RxJS.</p>`,
    lesson: 'rxjs-http',
  },
  {
    id: 'ng-flatten-typeahead', topic: 'angular', level: 2, type: 'mcq',
    question: 'Pour un champ de recherche (typeahead), quel opérateur d’aplatissement choisis-tu ?',
    choices: ['mergeMap', 'concatMap', 'switchMap', 'exhaustMap'],
    answer: 2,
    explanation: `<p><code>switchMap</code> <strong>annule</strong> la requête précédente dès qu’une nouvelle valeur arrive : on ne veut que le résultat de la dernière frappe. <code>mergeMap</code> garderait toutes les requêtes en vol (résultats dans le désordre), <code>concatMap</code> les mettrait en file (lent), <code>exhaustMap</code> ignorerait les nouvelles frappes tant qu’une requête est en cours.</p>`,
    lesson: 'rxjs-http',
  },
  {
    id: 'ng-flatten-save', topic: 'angular', level: 2, type: 'mcq',
    question: 'Un bouton « Payer » ne doit jamais déclencher deux paiements si l’utilisateur double-clique. Quel opérateur ?',
    choices: ['switchMap', 'exhaustMap', 'mergeMap', 'debounceTime(300)'],
    answer: 1,
    explanation: `<p><code>exhaustMap</code> ignore les nouvelles émissions tant que l’observable interne est en cours : le second clic est tout simplement jeté. <code>switchMap</code> annulerait la <em>souscription</em> côté client mais la requête HTTP serait déjà partie — le serveur paierait quand même. <code>debounceTime</code> retarderait le premier clic, ce qui n’empêche pas deux clics espacés de 400 ms.</p>`,
  },
  {
    id: 'ng-refresh-interceptor', topic: 'angular', level: 2, type: 'open',
    question: 'Comment implémentes-tu le rafraîchissement automatique du token sur une 401 dans un interceptor ? Quels pièges ?',
    keyPoints: [
      { text: 'catchError sur 401 → appeler /refresh → cloner la requête avec le nouveau token → la rejouer', keywords: ['catcherror', '401', 'refresh', 'clone', 'rejou', 'replay', 'retry'] },
      { text: 'Éviter la boucle : la requête de refresh elle-même ne doit pas être interceptée (HttpContextToken / URL exclue)', keywords: ['boucle', 'loop', 'httpcontexttoken', 'skip', 'exclu', 'infini'] },
      { text: 'Concurrence : N requêtes en 401 simultanées → un seul refresh partagé (shareReplay / promesse en cours)', keywords: ['concurren', 'simultan', 'sharereplay', 'partag', 'plusieurs requêtes', 'plusieurs requetes', 'file', 'queue'] },
      { text: 'Si le refresh échoue → logout + redirection login', keywords: ['logout', 'déconne', 'deconne', 'login', 'redirig'] },
    ],
    model: `<p>L’interceptor ajoute le Bearer, passe la main à <code>next()</code>, et dans un <code>catchError</code> détecte le 401. Il appelle le store pour obtenir un nouveau couple via <code>/refresh</code>, puis <code>switchMap</code> vers la requête clonée avec le nouveau token. Trois pièges : (1) la requête de refresh ne doit pas repasser par cette logique — un <code>HttpContextToken</code> <code>SKIP_AUTH</code> ou une exclusion d’URL ; (2) si cinq requêtes échouent en même temps, il ne faut lancer qu’<em>un</em> refresh et faire attendre les autres (un observable de refresh partagé avec <code>shareReplay(1)</code>, ou une file) ; (3) si le refresh échoue, on déconnecte proprement.</p>`,
    diagram: 'jwt', lesson: 'interceptors',
  },
  {
    id: 'ng-guards', topic: 'angular', level: 1, type: 'mcq',
    question: 'Différence entre canActivate et canMatch ?',
    choices: [
      'Aucune, canMatch est l’ancien nom.',
      'canActivate bloque ou redirige après que la route a matché ; canMatch, s’il échoue, laisse le routeur essayer la route suivante avec le même chemin (et n’a même pas téléchargé le chunk lazy).',
      'canMatch ne fonctionne qu’avec les routes enfants.',
      'canActivate est asynchrone, canMatch est synchrone.',
    ],
    answer: 1,
    explanation: `<p><code>canMatch</code> participe au <em>matching</em> : on peut déclarer deux fois <code>path: 'admin'</code> avec deux composants et deux guards, le routeur prend le premier qui passe. Et comme il tourne avant le chargement, le chunk lazy d’une route interdite n’est jamais téléchargé.</p>`,
    lesson: 'routing',
  },
  {
    id: 'ng-forms', topic: 'angular', level: 2, type: 'open',
    question: 'Reactive Forms ou Template-driven : lesquels choisis-tu et pourquoi ? Que sont les Signal Forms ?',
    keyPoints: [
      { text: 'Reactive : modèle dans le TS, typé (nonNullable), testable sans DOM', keywords: ['typ', 'test', 'nonnullable', 'formbuilder', 'formgroup'] },
      { text: 'Validateurs = fonctions pures composables (sync, async, cross-field)', keywords: ['validat', 'pure', 'async', 'cross', 'compos'] },
      { text: 'Formulaires dynamiques (FormArray) et réaction aux changements (valueChanges)', keywords: ['formarray', 'dynamique', 'valuechanges', 'statuschanges'] },
      { text: 'Template-driven pour les formulaires triviaux ; Signal Forms = nouvelle API basée signals (expérimentale)', keywords: ['template', 'ngmodel', 'simple', 'signal form', 'expériment', 'experiment'] },
    ],
    model: `<p>En entreprise, Reactive Forms par défaut : le modèle vit dans le TypeScript, il est typé (<code>fb.nonNullable.group</code>), testable sans rendre le DOM, et les validateurs sont des fonctions pures qu’on compose (sync, async avec appel API, cross-field sur le groupe). Les <code>FormArray</code> gèrent les listes dynamiques. Template-driven (<code>ngModel</code>) reste acceptable pour un formulaire de 2 champs. Les Signal Forms (v21+, expérimental) rapprochent les formulaires du modèle signals — à surveiller, pas encore le standard.</p>`,
    lesson: 'forms',
  },
  {
    id: 'ng-di-component-providers', topic: 'angular', level: 2, type: 'mcq',
    question: 'Un service est déclaré providedIn: "root" ET listé dans les providers d’un composant. Que se passe-t-il ?',
    choices: [
      'Erreur de compilation : double déclaration.',
      'Le composant et tout son sous-arbre reçoivent une NOUVELLE instance ; le reste de l’app garde l’instance root.',
      'Le provider du composant est ignoré, root gagne toujours.',
      'Angular crée deux instances root.',
    ],
    answer: 1,
    explanation: `<p>Les providers d’un composant créent un <strong>injecteur enfant</strong>. La résolution remonte l’arbre et s’arrête au premier provider trouvé : le sous-arbre voit sa propre instance. C’est utile (un état par instance de composant) et dangereux (deux parties de l’app croient partager un état alors que non).</p>`,
    lesson: 'di',
  },
  {
    id: 'ng-cd-zoneless', topic: 'angular', level: 3, type: 'open',
    question: 'En mode zoneless, qu’est-ce qui déclenche un rendu ? Cite un cas où la vue ne se met PAS à jour et comment le corriger.',
    keyPoints: [
      { text: 'Un signal lu dans le template qui change', keywords: ['signal'] },
      { text: 'Un événement du template ((click), (input)…)', keywords: ['événement', 'evenement', 'click', 'event', 'listener'] },
      { text: 'async pipe, markForCheck, changement d’input', keywords: ['async', 'markforcheck', 'input'] },
      { text: 'Cas cassé : setTimeout / promesse / callback tiers qui modifie une propriété classique → rien ne se passe', keywords: ['settimeout', 'propriété', 'propriete', 'callback', 'promise', 'tiers', 'third'] },
      { text: 'Correction : signal, ou ChangeDetectorRef.markForCheck / ApplicationRef.tick, ou runInInjectionContext', keywords: ['signal', 'markforcheck', 'tick', 'detectchanges', 'cdr'] },
    ],
    model: `<p>Sans zone.js, Angular ne patche plus <code>setTimeout</code>, <code>Promise</code>, <code>XHR</code>… Il re-rend quand : un signal lu par un template change, un event listener du template se déclenche, un <code>async</code> pipe reçoit une valeur, un input change, ou qu’on appelle <code>markForCheck()</code>. Le cas classique qui casse : un <code>setInterval</code> (ou un SDK tiers) qui incrémente <code>this.count++</code> — la valeur change en mémoire, l’écran non. Solution : en faire un <code>signal</code> (<code>count.update(...)</code>), ou appeler <code>cdr.markForCheck()</code> dans le callback.</p>`,
    diagram: 'signals', lesson: 'control-flow',
  },
  {
    id: 'ng-defer-triggers', topic: 'angular', level: 2, type: 'mcq',
    question: 'Lequel n’est PAS un trigger valide de @defer ?',
    choices: ['on viewport', 'on interaction', 'on scroll', 'on idle'],
    answer: 2,
    explanation: `<p>Les triggers : <code>on idle</code> (défaut), <code>on viewport</code>, <code>on interaction</code>, <code>on hover</code>, <code>on immediate</code>, <code>on timer(x)</code>, et <code>when &lt;condition&gt;</code>. On peut combiner avec <code>prefetch on …</code> pour télécharger le chunk avant de l’afficher. Il n’y a pas de <code>on scroll</code> : c’est <code>on viewport</code> qui couvre ce besoin.</p>`,
    lesson: 'control-flow',
  },
  {
    id: 'ng-model-input', topic: 'angular', level: 1, type: 'mcq',
    question: 'Que fait model() par rapport à input() ?',
    choices: [
      'model() est un input obligatoire.',
      'model() crée un input ET un output <nom>Change, ce qui permet le two-way binding [(x)] sans écrire l’output soi-même.',
      'model() est réservé aux formulaires.',
      'model() est un signal en lecture seule.',
    ],
    answer: 1,
    explanation: `<p><code>model()</code> retourne un signal <em>writable</em> : l’enfant fait <code>qty.set(3)</code>, le parent lié avec <code>[(qty)]="value"</code> voit son signal mis à jour. C’est l’équivalent moderne de la paire <code>@Input() qty</code> + <code>@Output() qtyChange</code>.</p>`,
    lesson: 'components',
  },
  {
    id: 'ng-perf', topic: 'angular', level: 3, type: 'open',
    question: 'Une page Angular est lente. Donne ta démarche et les leviers principaux.',
    keyPoints: [
      { text: 'Mesurer d’abord : DevTools Performance, Angular DevTools profiler, Lighthouse, bundle analyzer', keywords: ['mesur', 'profil', 'lighthouse', 'devtools', 'analyzer', 'audit'] },
      { text: 'Bundle : lazy loading, @defer, budgets, tree-shaking, éviter les libs lourdes', keywords: ['lazy', 'defer', 'bundle', 'chunk', 'budget', 'tree'] },
      { text: 'Rendu : OnPush / signals, track, pipes purs, éviter les fonctions dans le template', keywords: ['onpush', 'signal', 'track', 'pipe', 'fonction dans le template', 'getter'] },
      { text: 'Listes : virtual scroll (CDK), pagination', keywords: ['virtual', 'cdk', 'pagin'] },
      { text: 'Réseau/first paint : SSR + hydration, preload, NgOptimizedImage, cache HTTP', keywords: ['ssr', 'hydrat', 'preload', 'ngoptimizedimage', 'image', 'cache'] },
    ],
    model: `<p>D’abord mesurer, jamais deviner : Lighthouse pour le chargement, l’onglet Performance et Angular DevTools pour le runtime, <code>source-map-explorer</code> pour le bundle. Ensuite les leviers par famille : <strong>chargement</strong> (lazy routes, <code>@defer</code>, budgets, SSR/hydration, <code>NgOptimizedImage</code>) ; <strong>rendu</strong> (OnPush + signals, <code>track</code> correct, pipes purs, pas d’appels de fonction dans les templates) ; <strong>données</strong> (virtual scroll pour les grandes listes, pagination côté serveur, cache HTTP). Et re-mesurer après chaque changement.</p>`,
  },
  {
    id: 'ng-tosignal', topic: 'angular', level: 2, type: 'mcq',
    question: 'toSignal(obs$) : quand souscrit-il, et que vaut le signal avant la première émission ?',
    choices: [
      'Il souscrit à la première lecture du signal ; vaut null avant.',
      'Il souscrit immédiatement à sa création (eager), se désabonne à la destruction du contexte, et vaut undefined (ou initialValue) avant la première émission.',
      'Il souscrit dans ngOnInit ; vaut une promesse avant.',
      'Il ne souscrit jamais : il faut appeler .connect().',
    ],
    answer: 1,
    explanation: `<p><code>toSignal</code> souscrit tout de suite (c’est pour ça qu’il doit être appelé dans un contexte d’injection : champ de classe ou constructeur) et nettoie via <code>DestroyRef</code>. Sans <code>initialValue</code>, le type est <code>T | undefined</code> ; avec <code>{ requireSync: true }</code> il exige une émission synchrone (BehaviorSubject).</p>`,
    lesson: 'rxjs-http',
  },
  {
    id: 'ng-projection', topic: 'angular', level: 2, type: 'open',
    question: 'Content projection (ng-content) vs ng-template + ngTemplateOutlet : quand utiliser l’un ou l’autre ?',
    keyPoints: [
      { text: 'ng-content projette du contenu fourni par le parent, éventuellement par slot (select)', keywords: ['ng-content', 'projet', 'select', 'slot'] },
      { text: 'Le contenu projeté est TOUJOURS instancié par le parent, même si le slot n’est pas affiché', keywords: ['toujours', 'instanci', 'créé', 'cree', 'même si', 'meme si'] },
      { text: 'ng-template = contenu différé, instancié à la demande par le composant (ngTemplateOutlet / createEmbeddedView), avec un contexte', keywords: ['ng-template', 'templateoutlet', 'contexte', 'context', 'différ', 'differ', 'demande', 'embeddedview'] },
      { text: 'Cas typiques : layout/slots → ng-content ; listes/tableaux avec cellule personnalisable, répétition → ng-template', keywords: ['tableau', 'table', 'liste', 'répét', 'repet', 'layout', 'card'] },
    ],
    model: `<p><code>ng-content</code> sert au <em>layout</em> : une carte, un dialog, des slots nommés — le parent écrit le contenu, l’enfant le place. Limite : ce contenu est créé par le parent quoi qu’il arrive, on ne peut ni le répéter ni lui passer des données. <code>ng-template</code> + <code>ngTemplateOutlet</code> donne le contrôle à l’enfant : il instancie le template quand il veut, autant de fois qu’il veut, avec un <em>contexte</em> (<code>let-item</code>). C’est le pattern des tableaux à colonnes personnalisables et des directives structurelles.</p>`,
    lesson: 'components',
  },
  {
    id: 'ng-store-when', topic: 'angular', level: 2, type: 'open',
    question: 'Quand un store global (NgRx) est-il justifié, et que fais-tu sinon ?',
    keyPoints: [
      { text: 'Sinon : service providedIn root avec signal privé + computed publics (suffit à 80 % des apps)', keywords: ['service', 'providedin', 'signal', 'computed', 'privé', 'prive'] },
      { text: 'Store justifié quand l’état est partagé entre features sans lien de parenté, avec beaucoup d’écrivains', keywords: ['partag', 'plusieurs', 'feature', 'écrivain', 'ecrivain', 'global', 'complex'] },
      { text: 'Besoin de traçabilité / devtools / undo / time-travel', keywords: ['devtools', 'traç', 'trac', 'undo', 'time', 'debug', 'histor'] },
      { text: 'NgRx SignalStore : le compromis moderne (withState/withComputed/withMethods, rxMethod)', keywords: ['signalstore', 'withstate', 'patchstate', 'rxmethod'] },
    ],
    model: `<p>Par défaut, pas de store : un service <code>providedIn: 'root'</code> qui encapsule un signal privé et expose des <code>computed</code> et des méthodes suffit, et c’est testable. Un store structuré se justifie quand plusieurs features indépendantes lisent et écrivent le même état, quand on a besoin de devtools / traçabilité des actions, ou quand l’équipe est grande et veut une convention forte. Aujourd’hui je choisirais <code>@ngrx/signals</code> (SignalStore) plutôt que le NgRx classique : même rigueur, dix fois moins de boilerplate.</p>`,
    lesson: 'signals-state',
  },

  // ═══════════════════════════ .NET ═══════════════════════════
  {
    id: 'net-dbcontext-lifetime', topic: 'dotnet', level: 1, type: 'mcq',
    question: 'Pourquoi le DbContext EF Core est-il enregistré en Scoped ?',
    choices: [
      'Parce qu’il est lourd à créer.',
      'Parce qu’il n’est pas thread-safe et porte un change tracker : une instance par requête HTTP isole les unités de travail.',
      'Parce que Singleton est interdit pour les classes disposables.',
      'Par convention, Transient marcherait aussi bien.',
    ],
    answer: 1,
    explanation: `<p>Le <code>DbContext</code> est une <strong>unité de travail</strong> : il suit les entités chargées et calcule les <code>UPDATE</code> au <code>SaveChanges</code>. Partagé entre requêtes (Singleton), il mélangerait les entités de tout le monde et exploserait sous la concurrence. Transient fonctionnerait mais deux services d’une même requête auraient deux contextes → deux transactions.</p>`,
    diagram: 'lifetimes', lesson: 'di-lifetimes',
  },
  {
    id: 'net-captive', topic: 'dotnet', level: 2, type: 'open',
    question: 'Qu’est-ce qu’une « captive dependency » ? Donne l’exemple classique et la solution.',
    keyPoints: [
      { text: 'Un Singleton qui injecte un Scoped (ou Transient) : la dépendance est capturée pour toute la vie de l’app', keywords: ['singleton', 'scoped', 'captur', 'captive'] },
      { text: 'Exemple : BackgroundService / HostedService qui injecte un DbContext', keywords: ['backgroundservice', 'hostedservice', 'dbcontext', 'background'] },
      { text: 'Conséquence : contexte partagé entre requêtes, thread-unsafe, données périmées', keywords: ['partag', 'thread', 'périm', 'perim', 'fuite', 'concurren'] },
      { text: 'Détection : ValidateScopes lève une exception en Development', keywords: ['validatescopes', 'exception', 'development', 'développement'] },
      { text: 'Solution : IServiceScopeFactory.CreateScope() puis résoudre le service dans le scope', keywords: ['scopefactory', 'createscope', 'scope'] },
    ],
    model: `<p>Une captive dependency, c’est un service à longue durée de vie (Singleton) qui garde une référence vers un service à durée de vie plus courte (Scoped) : celui-ci est « captif », il ne meurt jamais. L’exemple universel : un <code>BackgroundService</code> qui injecte un <code>DbContext</code>. Résultat : un contexte partagé par tous les cycles du job, thread-unsafe, avec un change tracker qui grossit. En Development, <code>ValidateScopes</code> lève une exception au démarrage. La solution : injecter <code>IServiceScopeFactory</code>, créer un scope à chaque itération (<code>using var scope = factory.CreateScope()</code>) et résoudre le <code>DbContext</code> dedans.</p>`,
    diagram: 'lifetimes', lesson: 'di-lifetimes',
  },
  {
    id: 'net-middleware-order', topic: 'dotnet', level: 1, type: 'mcq',
    question: 'Quel ordre de middlewares est correct ?',
    choices: [
      'UseAuthorization → UseAuthentication → UseCors',
      'UseExceptionHandler → UseCors → UseAuthentication → UseAuthorization → MapEndpoints',
      'MapEndpoints → UseAuthentication → UseExceptionHandler',
      'L’ordre n’a pas d’importance, le framework trie automatiquement.',
    ],
    answer: 1,
    explanation: `<p>L’ordre d’enregistrement = l’ordre d’exécution. L’exception handler doit englober tout le reste. CORS doit répondre avant toute logique qui écrit une réponse. On <em>identifie</em> (Authentication) avant de <em>décider</em> (Authorization) — inversés, tout le monde est anonyme au moment de la décision → 401 partout.</p>`,
    diagram: 'pipeline', lesson: 'middleware',
  },
  {
    id: 'net-pipeline', topic: 'dotnet', level: 2, type: 'open',
    question: 'Explique le pipeline de middlewares ASP.NET Core. Comment un middleware court-circuite-t-il ?',
    keyPoints: [
      { text: 'Chaîne de RequestDelegate : chaque middleware reçoit next et décide de l’appeler', keywords: ['requestdelegate', 'next', 'chaîne', 'chaine', 'délégu', 'delegu'] },
      { text: 'Ordre = ordre des app.Use… ; la réponse remonte en sens inverse (oignon)', keywords: ['ordre', 'inverse', 'oignon', 'onion', 'retour'] },
      { text: 'Court-circuit = ne pas appeler next (ex. 401, rate limit, cache hit)', keywords: ['court', 'short', 'pas appeler', 'sans appeler', 'n’appelle pas', 'n\'appelle pas', 'return'] },
      { text: 'Use / Map / Run ; endpoint filters = même idée au niveau endpoint', keywords: ['use', 'map', 'run', 'filter'] },
    ],
    model: `<p>Le pipeline est une liste chaînée de <code>RequestDelegate</code> : chaque middleware reçoit le suivant (<code>next</code>) et la <code>HttpContext</code>. Il peut faire quelque chose avant d’appeler <code>next</code> (aller), après (retour), ou <strong>ne pas l’appeler du tout</strong> : c’est le court-circuit — un rate limiter qui répond 429, un cache de sortie qui sert la réponse stockée, un middleware d’auth qui répond 401. L’ordre est celui des <code>app.Use…</code> à l’aller et l’inverse au retour, d’où l’image de l’oignon.</p>`,
    diagram: 'pipeline', lesson: 'middleware',
  },
  {
    id: 'net-minimal-binding', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'Dans une Minimal API, MapPost("/x", (Product p, int id, AppDbContext db) => …) : d’où viennent p, id et db ?',
    choices: [
      'Tous les trois du body JSON.',
      'p du body (type complexe), id de la route ou de la query string (type simple), db de l’injection de dépendances (type enregistré).',
      'p de la query string, id de la route, db du body.',
      'Il faut obligatoirement [FromBody], [FromRoute], [FromServices].',
    ],
    answer: 1,
    explanation: `<p>Le binding est par convention : types simples → route puis query ; types complexes → body JSON (un seul par endpoint) ; types connus du conteneur → DI ; <code>HttpContext</code>, <code>ClaimsPrincipal</code>, <code>CancellationToken</code> → contexte. Les attributs <code>[FromXxx]</code> ne servent qu’à lever une ambiguïté.</p>`,
    lesson: 'minimal-vs-controllers',
  },
  {
    id: 'net-iqueryable', topic: 'dotnet', level: 2, type: 'open',
    question: 'IQueryable vs IEnumerable avec EF Core : quelle différence, et quand la requête SQL part-elle vraiment ?',
    keyPoints: [
      { text: 'IQueryable = arbre d’expression traduit en SQL ; IEnumerable = exécution en mémoire', keywords: ['expression', 'sql', 'mémoire', 'memoire', 'traduit', 'linq to'] },
      { text: 'Exécution différée : la requête part à l’énumération (ToList, First, Count, foreach, await)', keywords: ['différ', 'differ', 'tolist', 'first', 'count', 'foreach', 'énumér', 'enumer', 'lazy'] },
      { text: 'Piège : un ToList() trop tôt (ou AsEnumerable) ramène toute la table puis filtre en mémoire', keywords: ['tolist', 'toute la table', 'asenumerable', 'mémoire', 'memoire', 'trop tôt', 'trop tot'] },
      { text: 'Optimisations : AsNoTracking en lecture, projection Select vers DTO, pagination Skip/Take', keywords: ['asnotracking', 'select', 'projection', 'dto', 'skip', 'take', 'pagin'] },
    ],
    model: `<p><code>IQueryable</code> ne contient pas de données : c’est un arbre d’expression que le provider EF traduit en SQL <em>au moment de l’énumération</em> — <code>ToListAsync</code>, <code>FirstOrDefault</code>, <code>Count</code>, <code>foreach</code>. Tant qu’on reste en <code>IQueryable</code>, <code>Where</code>, <code>OrderBy</code>, <code>Skip/Take</code> s’ajoutent au SQL. Dès qu’on passe en <code>IEnumerable</code> (après <code>ToList()</code> ou <code>AsEnumerable()</code>), tout ce qui suit s’exécute en mémoire sur ce qui a été ramené — le bug classique est un <code>ToList()</code> avant un <code>Where</code> qui charge toute la table. En lecture, <code>AsNoTracking</code> et une projection <code>Select</code> vers un DTO évitent le change tracker et ne chargent que les colonnes utiles.</p>`,
    lesson: 'ef-core',
  },
  {
    id: 'net-n1', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'Tu listes 100 commandes puis, dans une boucle, tu accèdes à order.Customer.Name. EF envoie 101 requêtes. Quelle est la meilleure correction ?',
    choices: [
      'Activer le lazy loading.',
      'Include(o => o.Customer) ou, mieux, une projection Select vers un DTO qui ne prend que les colonnes nécessaires — une seule requête.',
      'Mettre le résultat en cache.',
      'Passer le DbContext en Singleton pour réutiliser les entités.',
    ],
    answer: 1,
    explanation: `<p>C’est le problème <strong>N+1</strong>. <code>Include</code> fait un JOIN (ou une requête séparée avec <code>AsSplitQuery</code>) ; la projection <code>Select(o => new { o.Id, Customer = o.Customer.Name })</code> est encore mieux : une requête, seulement les colonnes utiles, pas de tracking. Le lazy loading est précisément ce qui <em>cause</em> le N+1.</p>`,
    lesson: 'ef-core',
  },
  {
    id: 'net-migrations-prod', topic: 'dotnet', level: 3, type: 'open',
    question: 'Comment gères-tu les migrations EF Core en production, avec plusieurs instances de l’API ?',
    keyPoints: [
      { text: 'Migrations versionnées dans le repo (migrations add), revues comme du code', keywords: ['migrations add', 'versionn', 'revue', 'review', 'repo', 'git'] },
      { text: 'Ne PAS appeler Migrate() au démarrage de l’app en multi-instance (course, verrous)', keywords: ['démarrage', 'demarrage', 'startup', 'migrate()', 'course', 'race', 'verrou', 'lock', 'instance'] },
      { text: 'Appliquer via un job/étape de pipeline dédié : script SQL idempotent (migrations script --idempotent) ou bundle', keywords: ['script', 'idempotent', 'bundle', 'pipeline', 'job', 'ci', 'étape', 'etape'] },
      { text: 'Compatibilité ascendante : expand/contract (ajouter, migrer, supprimer plus tard) pour le zero-downtime', keywords: ['expand', 'contract', 'compatib', 'zero', 'downtime', 'rétro', 'retro', 'deux versions'] },
      { text: 'Backup + Down/rollback testés, séparer schéma et données', keywords: ['backup', 'sauvegarde', 'down', 'rollback', 'données', 'donnees'] },
    ],
    model: `<p>Les migrations sont du code : générées par <code>dotnet ef migrations add</code>, commitées, relues (le SQL généré aussi). En production je n’appelle jamais <code>Database.Migrate()</code> au démarrage quand il y a plusieurs instances : deux pods qui migrent en même temps, c’est une course. J’applique la migration dans une étape dédiée du déploiement — <code>migrations script --idempotent</code> ou un <em>migration bundle</em> — avant de basculer le trafic. Pour le zero-downtime, le schéma doit rester compatible avec l’ancienne version pendant le rollout : pattern expand/contract (ajouter la colonne, déployer, migrer les données, supprimer l’ancienne colonne plus tard). Et un backup avant, un rollback testé.</p>`,
    lesson: 'ef-core',
  },
  {
    id: 'net-problemdetails', topic: 'dotnet', level: 1, type: 'mcq',
    question: 'Qu’est-ce que ProblemDetails (RFC 9457) ?',
    choices: [
      'Un format de log structuré.',
      'Un format JSON standard pour les réponses d’erreur HTTP : type, title, status, detail, instance, + extensions (errors, traceId).',
      'Le format des exceptions .NET sérialisées.',
      'Un middleware de validation.',
    ],
    answer: 1,
    explanation: `<p>Tous les clients (Angular, mobile, partenaires) parlent le même langage d’erreur. ASP.NET le produit via <code>AddProblemDetails()</code>, <code>Results.Problem()</code>, <code>ValidationProblem()</code>. Règle d’or : <code>detail</code> ne contient jamais de stack trace en production.</p>`,
    lesson: 'middleware',
  },
  {
    id: 'net-result-vs-exceptions', topic: 'dotnet', level: 2, type: 'open',
    question: 'Exceptions ou pattern Result pour les erreurs métier ? Argumente.',
    keyPoints: [
      { text: 'Exception = cas inattendu (bug, infra) ; Result = échec attendu du métier (introuvable, stock insuffisant)', keywords: ['inattendu', 'attendu', 'métier', 'metier', 'bug', 'infra', 'normal'] },
      { text: 'Le type force l’appelant à gérer l’échec (Match) ; une exception peut être oubliée', keywords: ['force', 'oubli', 'match', 'explicite', 'signature', 'type'] },
      { text: 'Coût : les exceptions sont chères et cassent le flux de lecture', keywords: ['coût', 'cout', 'cher', 'perf', 'flux', 'lisib', 'goto'] },
      { text: 'Mapping centralisé Error → HTTP (404/409/400) ; codes d’erreur stables', keywords: ['mapping', 'central', '404', '409', 'code', 'problem'] },
      { text: 'Ne pas abuser : Result partout devient du bruit ; garder un exception handler global', keywords: ['abus', 'partout', 'bruit', 'global', 'handler', 'équilibre', 'equilibre'] },
    ],
    model: `<p>Une exception est pour ce qui ne devrait pas arriver : base injoignable, bug. « Produit introuvable » ou « stock insuffisant » sont des résultats <em>normaux</em> d’une commande : les modéliser comme <code>Result&lt;T&gt;</code> avec une <code>Error</code> typée rend l’échec visible dans la signature, force l’appelant à le traiter, et évite le coût et le côté « goto » des exceptions. Un mapping central transforme chaque type d’erreur en statut HTTP + ProblemDetails avec un code stable. Mais je garde un <code>IExceptionHandler</code> global pour l’inattendu, et je n’enveloppe pas <em>tout</em> dans des Result — sinon le code devient illisible.</p>`,
    lesson: 'vertical-slice',
  },
  {
    id: 'net-options', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'Un Singleton doit lire une option de configuration qui peut changer à chaud. Quelle interface injecter ?',
    choices: ['IOptions<T>', 'IOptionsSnapshot<T>', 'IOptionsMonitor<T>', 'IConfiguration directement'],
    answer: 2,
    explanation: `<p><code>IOptions</code> est figé au premier accès. <code>IOptionsSnapshot</code> est <em>Scoped</em> : l’injecter dans un Singleton est une captive dependency (et lève une exception). <code>IOptionsMonitor</code> est Singleton, expose <code>CurrentValue</code> et <code>OnChange</code>.</p>`,
    lesson: 'options',
  },
  {
    id: 'net-async', topic: 'dotnet', level: 2, type: 'open',
    question: 'Pourquoi async/await partout dans une API ASP.NET Core ? Quels sont les pièges ?',
    keyPoints: [
      { text: 'Libère le thread pendant les I/O (DB, HTTP) → plus de requêtes simultanées avec le même thread pool', keywords: ['thread', 'libère', 'libere', 'i/o', 'io', 'pool', 'scalab', 'simultan', 'bloqu'] },
      { text: 'Pièges : .Result / .Wait() / GetAwaiter().GetResult() → thread pool starvation, deadlocks', keywords: ['.result', 'wait()', 'getresult', 'starvation', 'deadlock', 'bloquant', 'sync over async'] },
      { text: 'async void interdit (sauf handlers d’événements) : exceptions perdues', keywords: ['async void', 'void'] },
      { text: 'Propager le CancellationToken jusqu’à EF / HttpClient', keywords: ['cancellationtoken', 'cancellation', 'annul'] },
      { text: 'ConfigureAwait(false) inutile en ASP.NET Core (pas de SynchronizationContext)', keywords: ['configureawait', 'synchronizationcontext'] },
    ],
    model: `<p>Une API passe son temps à attendre la base ou d’autres services. Avec <code>await</code>, le thread est rendu au pool pendant l’attente et peut servir une autre requête : c’est ce qui permet des milliers de requêtes concurrentes avec quelques dizaines de threads. Les pièges : bloquer avec <code>.Result</code> ou <code>.Wait()</code> (thread pool starvation, parfois deadlock), <code>async void</code> (exception non observée qui tue le process), oublier de propager le <code>CancellationToken</code> (les requêtes annulées continuent de tourner). Et en ASP.NET Core, <code>ConfigureAwait(false)</code> ne sert à rien : il n’y a pas de SynchronizationContext.</p>`,
  },
  {
    id: 'net-background-db', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'Un BackgroundService doit écrire en base toutes les minutes. Comment obtenir un DbContext ?',
    choices: [
      'L’injecter dans le constructeur du BackgroundService.',
      'Injecter IServiceScopeFactory, créer un scope à chaque itération et résoudre le DbContext dans ce scope.',
      'Enregistrer le DbContext en Singleton.',
      'Utiliser new AppDbContext() directement.',
    ],
    answer: 1,
    explanation: `<p>Le <code>BackgroundService</code> est un Singleton ; injecter un Scoped dedans est une captive dependency. Un scope par itération = un contexte frais, éliminé à la fin (<code>using</code>), exactement comme une requête HTTP.</p>`,
    diagram: 'lifetimes', lesson: 'realtime',
  },
  {
    id: 'net-caching', topic: 'dotnet', level: 3, type: 'open',
    question: 'IMemoryCache, IDistributedCache, HybridCache, OutputCache : lequel pour quoi ? Comment invalides-tu ?',
    keyPoints: [
      { text: 'IMemoryCache : local au process, rapide, incohérent en multi-instances', keywords: ['memorycache', 'local', 'process', 'instance', 'incohér', 'incoher'] },
      { text: 'IDistributedCache (Redis) : partagé entre instances, sérialisation, latence réseau', keywords: ['distributed', 'redis', 'partag', 'sérial', 'serial', 'réseau', 'reseau'] },
      { text: 'HybridCache (.NET 9+) : L1 mémoire + L2 distribué, protection contre le cache stampede', keywords: ['hybrid', 'l1', 'l2', 'stampede', 'deux niveaux'] },
      { text: 'OutputCache : la réponse HTTP entière, avec policies, VaryBy, tags', keywords: ['output', 'réponse', 'reponse', 'http', 'policy', 'varyby', 'tag'] },
      { text: 'Invalidation : TTL absolu/glissant, tags (EvictByTag), clé versionnée, événements', keywords: ['ttl', 'expir', 'tag', 'evict', 'invalid', 'version', 'événement', 'evenement'] },
    ],
    model: `<p><code>IMemoryCache</code> vit dans le process : idéal pour des données petites et tolérantes à une légère incohérence entre instances. Dès qu’il y a plusieurs instances et qu’on veut une seule vérité, <code>IDistributedCache</code> sur Redis — au prix de la sérialisation et d’un aller-retour réseau. <code>HybridCache</code> combine les deux (L1 local, L2 Redis) et gère le <em>stampede</em> : cent requêtes simultanées sur une clé expirée ne déclenchent qu’un seul calcul. <code>OutputCache</code> est différent : il cache la réponse HTTP complète, le handler n’est même pas exécuté, avec des policies (<code>VaryByQuery</code>, tags). Invalidation : TTL courts par défaut, <code>EvictByTag</code> quand on écrit, ou une clé qui inclut une version.</p>`,
    lesson: 'caching',
  },
  {
    id: 'net-ratelimit-algos', topic: 'dotnet', level: 1, type: 'mcq',
    question: 'Quel algorithme n’est PAS fourni par le rate limiter intégré d’ASP.NET Core ?',
    choices: ['Fixed window', 'Sliding window', 'Token bucket', 'Leaky bucket'],
    answer: 3,
    explanation: `<p>Le middleware fournit fixed window, sliding window, token bucket et <em>concurrency</em> (nombre de requêtes simultanées). Le leaky bucket n’y est pas (on le trouve dans des reverse proxies). On partitionne par IP, utilisateur, API key… et on répond 429 + <code>Retry-After</code>.</p>`,
    lesson: 'caching',
  },
  {
    id: 'net-testing', topic: 'dotnet', level: 3, type: 'open',
    question: 'Quelle stratégie de tests pour une API .NET ? Comment testes-tu avec la base de données ?',
    keyPoints: [
      { text: 'Pyramide : unitaires sur la logique pure (validators, handlers, domain), intégration sur le pipeline HTTP, quelques E2E', keywords: ['pyramide', 'unitaire', 'intégration', 'integration', 'e2e', 'end-to-end'] },
      { text: 'WebApplicationFactory<Program> : la vraie app en mémoire, vrais middlewares, vraie auth', keywords: ['webapplicationfactory', 'factory', 'in-memory', 'mémoire', 'memoire', 'pipeline'] },
      { text: 'DB : Testcontainers (vraie base éphémère) > SQLite fichier jetable > InMemory provider (à éviter : comportement différent)', keywords: ['testcontainers', 'docker', 'sqlite', 'inmemory', 'éphém', 'ephem', 'jetable', 'vrai'] },
      { text: 'Overrides : ConfigureAppConfiguration / ConfigureTestServices, remplacer les dépendances externes', keywords: ['configure', 'override', 'remplac', 'mock', 'stub', 'fake'] },
      { text: 'Tests d’architecture (NetArchTest) et tests de contrat', keywords: ['architecture', 'netarchtest', 'archunit', 'contrat', 'contract'] },
    ],
    model: `<p>Beaucoup de tests d’intégration via <code>WebApplicationFactory&lt;Program&gt;</code> : ils démarrent la vraie application en mémoire — routing, filtres, auth, EF — et un scénario HTTP réaliste vaut dix mocks. Pour la base, je préfère une vraie base éphémère (Testcontainers avec Postgres) ; SQLite est un compromis acceptable ; le provider InMemory est à éviter car il n’a pas le même comportement (pas de contraintes, pas de SQL). Les dépendances externes (paiement, email) sont remplacées via <code>ConfigureTestServices</code>. Des tests unitaires pour la logique pure (validators, calculs), et des tests d’architecture pour garder les frontières.</p>`,
    lesson: 'testing',
  },
  {
    id: 'net-records', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'À propos des records C#, quelle affirmation est vraie ?',
    choices: [
      'Un record est toujours immuable.',
      'Deux records de même type avec les mêmes valeurs sont égaux (égalité structurelle), et l’expression with crée une copie modifiée.',
      'Un record ne peut pas avoir de méthodes.',
      'record struct n’existe pas.',
    ],
    answer: 1,
    explanation: `<p>Les records apportent l’égalité par valeur, un <code>ToString</code> lisible, la déconstruction et <code>with</code>. Ils sont immuables <em>par défaut</em> avec la syntaxe positionnelle (propriétés <code>init</code>), mais rien n’empêche d’y mettre un <code>set</code>. <code>record struct</code> existe (C# 10). Parfaits pour les DTOs, requêtes, événements, erreurs.</p>`,
  },
  {
    id: 'net-signalr', topic: 'dotnet', level: 2, type: 'open',
    question: 'Comment fonctionne SignalR, et comment le fais-tu tenir avec plusieurs instances de l’API ?',
    keyPoints: [
      { text: 'Négociation du transport : WebSockets, sinon Server-Sent Events, sinon long polling', keywords: ['websocket', 'sse', 'server-sent', 'long polling', 'négoci', 'negoci', 'transport'] },
      { text: 'RPC bidirectionnel : le serveur appelle des méthodes client, le client invoque des méthodes du hub', keywords: ['rpc', 'bidirection', 'hub', 'invoke', 'méthode', 'methode'] },
      { text: 'Groups, IHubContext pour pousser depuis un endpoint ou un job', keywords: ['group', 'hubcontext', 'pousser', 'push', 'endpoint', 'job'] },
      { text: 'Multi-instances : backplane Redis (ou Azure SignalR Service) pour relayer les messages', keywords: ['backplane', 'redis', 'azure signalr', 'instance', 'scale', 'relay', 'sticky'] },
      { text: 'Auth : token en query string pour WebSockets (OnMessageReceived)', keywords: ['query', 'token', 'onmessagereceived', 'auth'] },
    ],
    model: `<p>SignalR abstrait le temps réel : il négocie le meilleur transport (WebSockets, sinon SSE, sinon long polling) et expose un RPC typé dans les deux sens — le serveur appelle <code>Clients.All.Tick(...)</code>, le client fait <code>invoke('SendMessage')</code>. Les <em>groups</em> ciblent des sous-ensembles ; <code>IHubContext</code> permet de pousser depuis n’importe où (endpoint HTTP, BackgroundService). Avec plusieurs instances, un client connecté au pod A ne reçoit pas ce que le pod B envoie : il faut un <strong>backplane</strong> Redis (ou Azure SignalR Service) qui rediffuse les messages à toutes les instances. Pour l’auth, les WebSockets ne portent pas de header : le token passe en query string, récupéré dans <code>OnMessageReceived</code>.</p>`,
    lesson: 'realtime',
  },
  {
    id: 'net-executeupdate', topic: 'dotnet', level: 2, type: 'mcq',
    question: 'Pour décrémenter un stock de façon sûre face à deux commandes simultanées, que préfères-tu ?',
    choices: [
      'Charger l’entité, faire stock -= qty, SaveChanges.',
      'Une mise à jour ensembliste conditionnelle : ExecuteUpdateAsync avec Where(p => p.Stock >= qty), puis vérifier le nombre de lignes affectées.',
      'Un lock C# autour du SaveChanges.',
      'Un cache mémoire du stock.',
    ],
    answer: 1,
    explanation: `<p>Load-modify-save est une <em>race</em> : deux requêtes lisent 5, écrivent 4 chacune. <code>ExecuteUpdateAsync</code> génère <code>UPDATE … SET Stock = Stock - @qty WHERE Id = @id AND Stock >= @qty</code> : atomique côté base. Alternative : un token de concurrence optimiste (<code>[ConcurrencyCheck]</code> / rowversion) et gérer <code>DbUpdateConcurrencyException</code>. Un <code>lock</code> C# ne protège qu’une instance de l’API.</p>`,
    lesson: 'modular-monolith',
  },

  // ═══════════════════════════ AUTH ═══════════════════════════
  {
    id: 'auth-jwt-readable', topic: 'auth', level: 1, type: 'mcq',
    question: 'Un JWT signé en HS256 est intercepté. Que peut faire l’attaquant ?',
    choices: [
      'Rien, le contenu est chiffré.',
      'Lire tout le payload (il est seulement encodé en base64url) et rejouer le token jusqu’à son expiration, mais pas le modifier sans la clé.',
      'Modifier le payload : la signature n’est vérifiée qu’au login.',
      'Générer d’autres tokens : la clé est dans le header.',
    ],
    answer: 1,
    explanation: `<p>Signer ≠ chiffrer. Le payload est lisible par n’importe qui : n’y mettez jamais de données sensibles. La signature garantit l’intégrité (toute modification l’invalide) ; le vol permet le rejeu jusqu’à <code>exp</code> — d’où les tokens courts, HTTPS obligatoire, et un stockage prudent côté client.</p>`,
    diagram: 'jwt', lesson: 'auth-jwt',
  },
  {
    id: 'auth-refresh-why', topic: 'auth', level: 2, type: 'open',
    question: 'Pourquoi un access token court + un refresh token ? Comment révoques-tu un JWT ?',
    keyPoints: [
      { text: 'JWT stateless : le serveur ne peut pas le révoquer avant exp → il doit être court (5–15 min)', keywords: ['stateless', 'révoqu', 'revoqu', 'court', 'minute', 'exp'] },
      { text: 'Refresh token opaque, stocké côté serveur → révocable, longue durée', keywords: ['opaque', 'serveur', 'base', 'stock', 'révocable', 'revocable', 'longue'] },
      { text: 'Rotation : chaque refresh consomme le token et en émet un nouveau ; réutilisation = vol détecté → révoquer la famille', keywords: ['rotation', 'consomm', 'usage unique', 'réutilis', 'reutilis', 'famille', 'vol'] },
      { text: 'Logout = révoquer les refresh ; l’access reste valide jusqu’à exp (acceptable s’il est court)', keywords: ['logout', 'déconnexion', 'deconnexion', 'reste valide'] },
      { text: 'Si révocation immédiate requise : blacklist de jti / version d’utilisateur vérifiée à chaque requête (on perd le stateless)', keywords: ['blacklist', 'jti', 'version', 'liste', 'deny', 'chaque requête', 'chaque requete'] },
    ],
    model: `<p>Un JWT est vérifié sans toucher la base — c’est sa force et sa faiblesse : on ne peut pas le « supprimer ». La parade : un access token très court (quelques minutes), et un refresh token opaque, aléatoire, <em>stocké</em> côté serveur, qu’on peut donc révoquer. À chaque refresh on fait tourner le token (l’ancien meurt) ; si un ancien token est présenté, c’est qu’il a été volé → on révoque toute la famille. Le logout révoque les refresh ; l’access token expire tout seul quelques minutes plus tard. Si le métier exige une révocation instantanée (compte bloqué), il faut une vérification par requête — liste de <code>jti</code> révoqués ou numéro de version de l’utilisateur — et on accepte de perdre un peu de stateless.</p>`,
    diagram: 'jwt', lesson: 'auth-jwt',
  },
  {
    id: 'auth-cookie-vs-jwt', topic: 'auth', level: 2, type: 'open',
    question: 'Cookie de session ou JWT ? Dans quels cas chacun, avec quels risques ?',
    keyPoints: [
      { text: 'Cookie HttpOnly : illisible par JS (XSS ne le vole pas), envoyé automatiquement → exposé au CSRF', keywords: ['httponly', 'xss', 'automatique', 'csrf'] },
      { text: 'Cookie : idéal même domaine / app web classique ; serveur stateful ou ticket chiffré', keywords: ['même domaine', 'meme domaine', 'même origine', 'meme origine', 'web', 'stateful', 'ticket', 'chiffr'] },
      { text: 'JWT : multi-clients (mobile, services), APIs stateless, scale horizontal', keywords: ['mobile', 'service', 'client', 'stateless', 'scale', 'horizontal', 'microservice'] },
      { text: 'JWT : stockage côté JS exposé au XSS, pas de révocation avant exp', keywords: ['localstorage', 'xss', 'révoc', 'revoc', 'stock'] },
      { text: 'Hybride BFF : le front parle cookie au backend, qui gère les tokens', keywords: ['bff', 'hybride', 'backend for frontend', 'proxy'] },
    ],
    model: `<p>Pour une application web servie sur le même domaine que son API, le cookie <code>HttpOnly</code> reste la solution la plus simple et la plus sûre : JavaScript ne peut pas le lire, donc une faille XSS ne vole pas la session ; en échange il faut se protéger du CSRF (<code>SameSite</code> + antiforgery). Le JWT s’impose quand l’API est consommée par plusieurs clients (mobile, partenaires, autres services) ou quand on veut un backend stateless qui scale horizontalement ; le prix : un stockage côté client exposé au XSS et l’impossibilité de révoquer avant expiration. Le pattern hybride « BFF » combine les deux : la SPA parle cookie à un backend qui, lui, manipule les tokens.</p>`,
    diagram: 'cookie-vs-jwt', lesson: 'auth-cookie',
  },
  {
    id: 'auth-csrf-defense', topic: 'auth', level: 2, type: 'mcq',
    question: 'Laquelle de ces mesures ne protège PAS contre le CSRF ?',
    choices: ['SameSite=Lax/Strict sur le cookie', 'Token antiforgery (double submit : cookie + header X-XSRF-TOKEN)', 'Flag HttpOnly sur le cookie de session', 'Vérifier l’en-tête Origin/Referer'],
    answer: 2,
    explanation: `<p><code>HttpOnly</code> protège contre le <strong>XSS</strong> (vol du cookie par un script), pas contre le CSRF : le navigateur envoie le cookie de toute façon quand un site tiers déclenche la requête. Les vraies défenses : <code>SameSite</code>, un token que l’attaquant ne peut pas lire (antiforgery), et la vérification d’origine.</p>`,
    lesson: 'auth-cookie',
  },
  {
    id: 'auth-pkce', topic: 'auth', level: 3, type: 'open',
    question: 'Explique le flow Authorization Code + PKCE pour une SPA. Pourquoi l’implicit flow est-il déprécié ?',
    keyPoints: [
      { text: 'La SPA génère code_verifier (aléatoire) et code_challenge = base64url(sha256(verifier))', keywords: ['verifier', 'challenge', 'sha256', 'aléatoire', 'aleatoire', 'random'] },
      { text: 'Redirection vers l’IdP avec challenge + state ; l’utilisateur s’authentifie chez l’IdP', keywords: ['redirect', 'redirig', 'idp', 'state', 'authorize'] },
      { text: 'Retour avec un code à usage unique ; vérification du state (anti-CSRF)', keywords: ['code', 'usage unique', 'state', 'callback'] },
      { text: 'Échange back-channel POST /token avec code + verifier ; l’IdP recalcule le hash', keywords: ['token', 'échange', 'echange', 'post', 'verifier', 'hash', 'back'] },
      { text: 'Implicit : tokens dans le fragment d’URL (historique, referer, logs), pas de preuve de possession', keywords: ['implicit', 'fragment', 'url', 'historique', 'referer', 'log', 'possession'] },
      { text: 'id_token vérifié (signature, iss, aud, nonce) ; access token pour l’API', keywords: ['id_token', 'nonce', 'signature', 'iss', 'aud', 'access'] },
    ],
    model: `<p>La SPA génère un secret éphémère, le <code>code_verifier</code>, et envoie seulement son hash (<code>code_challenge</code>) à l’IdP lors de la redirection, avec un <code>state</code> aléatoire. L’utilisateur se connecte <em>chez l’IdP</em> (l’app ne voit jamais le mot de passe). L’IdP redirige vers l’app avec un <code>code</code> à usage unique. L’app vérifie le <code>state</code>, puis échange le code contre les tokens par un POST direct (<em>back-channel</em>) en fournissant le <code>code_verifier</code> : l’IdP recalcule le hash et refuse s’il ne correspond pas. Un code intercepté est donc inutile sans le verifier. L’implicit flow renvoyait les tokens directement dans le fragment d’URL — exposés à l’historique, au referer, aux logs — sans aucune preuve de possession ; il est déprécié. Enfin l’<code>id_token</code> est vérifié (signature, <code>iss</code>, <code>aud</code>, <code>nonce</code>) et l’<code>access_token</code> sert à appeler l’API.</p>`,
    diagram: 'pkce', lesson: 'auth-oidc',
  },
  {
    id: 'auth-401-403', topic: 'auth', level: 1, type: 'mcq',
    question: 'Authentification vs autorisation, 401 vs 403 ?',
    choices: [
      'Authentification = « qui es-tu » (échec → 401) ; autorisation = « as-tu le droit » (échec → 403).',
      'C’est la même chose, 401 et 403 sont interchangeables.',
      'Authentification → 403, autorisation → 401.',
      '401 signifie « ressource introuvable pour cet utilisateur ».',
    ],
    answer: 0,
    explanation: `<p>401 Unauthorized est mal nommé : il veut dire « non authentifié, présente des identifiants » (avec un header <code>WWW-Authenticate</code>). 403 Forbidden : « je sais qui tu es, et non ». Dans ASP.NET : <code>UseAuthentication</code> produit le <code>ClaimsPrincipal</code>, <code>UseAuthorization</code> évalue les policies.</p>`,
    lesson: 'authorization',
  },
  {
    id: 'auth-policies', topic: 'auth', level: 2, type: 'open',
    question: 'Rôles, claims, policies : comment structures-tu les permissions dans une API ASP.NET Core ?',
    keyPoints: [
      { text: 'Rôles = groupes grossiers (Admin, User) ; pratiques mais rigides', keywords: ['rôle', 'role', 'grossier', 'groupe', 'rigide'] },
      { text: 'Claims de permission fines (products:write) découplées des rôles', keywords: ['claim', 'permission', 'fin', 'granul', 'découpl', 'decoupl'] },
      { text: 'Policy = requirements + handlers ; le code n’attache que des noms de policy', keywords: ['policy', 'requirement', 'handler', 'nom'] },
      { text: 'Resource-based : IAuthorizationService.AuthorizeAsync(user, ressource, policy) quand la décision dépend de la donnée', keywords: ['resource', 'ressource', 'authorizeasync', 'iauthorizationservice', 'propriétaire', 'proprietaire', 'owner'] },
      { text: 'Les claims sont la monnaie commune : toutes les schemes (JWT, cookie, API key) en produisent', keywords: ['scheme', 'commun', 'monnaie', 'claimsprincipal', 'jwt', 'cookie', 'api key'] },
    ],
    model: `<p>Les rôles sont pratiques pour des groupes larges, mais « Admin peut tout » devient vite faux. Je préfère des <em>permissions</em> fines portées par des claims (<code>products:write</code>) et des rôles qui ne sont que des paquets de permissions. Le code ne teste jamais un rôle en dur : il attache une <em>policy</em> nommée, et la policy — requirements + handlers — encapsule la règle ; changer la règle ne touche pas les endpoints. Quand la décision dépend de la ressource (« seulement le propriétaire du document »), on passe en resource-based avec <code>IAuthorizationService</code>. Et comme toutes les schemes produisent un <code>ClaimsPrincipal</code>, la même policy fonctionne qu’on vienne d’un JWT, d’un cookie ou d’une API key.</p>`,
    lesson: 'authorization',
  },
  {
    id: 'auth-hs-rs', topic: 'auth', level: 2, type: 'mcq',
    question: 'Trois APIs doivent vérifier les tokens émis par un même serveur d’identité. HS256 ou RS256 ?',
    choices: [
      'HS256 : plus rapide.',
      'RS256/ES256 : l’émetteur signe avec sa clé privée, les APIs vérifient avec la clé publique (JWKS) — aucune API ne détient le secret.',
      'HS256 avec la même clé partagée sur les trois APIs.',
      'Peu importe, la sécurité est identique.',
    ],
    answer: 1,
    explanation: `<p>Avec HS256 (symétrique), quiconque peut <em>vérifier</em> peut aussi <em>signer</em> : partager la clé avec trois APIs, c’est trois endroits d’où forger des tokens. Avec RS256 (asymétrique), les APIs téléchargent les clés publiques via <code>/.well-known/jwks.json</code> et ne peuvent que vérifier. HS256 reste correct quand émetteur = consommateur.</p>`,
    lesson: 'auth-oidc',
  },
  {
    id: 'auth-token-storage', topic: 'auth', level: 2, type: 'open',
    question: 'Où stockes-tu les tokens dans une SPA Angular ? Justifie.',
    keyPoints: [
      { text: 'localStorage = lisible par tout script → XSS vole le token ; à éviter pour des tokens longs', keywords: ['localstorage', 'xss', 'script', 'éviter', 'eviter'] },
      { text: 'Access token en mémoire (signal/variable), courte durée', keywords: ['mémoire', 'memoire', 'memory', 'signal', 'variable', 'court'] },
      { text: 'Refresh token en cookie HttpOnly + SameSite (pattern BFF) : JS ne le voit jamais', keywords: ['httponly', 'cookie', 'samesite', 'bff'] },
      { text: 'Jamais dans l’URL ; CSP pour réduire le XSS', keywords: ['url', 'csp', 'content security'] },
    ],
    model: `<p>Le vrai risque d’une SPA, c’est le XSS : tout ce que JavaScript peut lire, un script injecté peut l’exfiltrer. Donc pas de refresh token en <code>localStorage</code>. Le compromis solide : l’access token vit en mémoire (un signal), il est court, et le refresh token est un cookie <code>HttpOnly</code> <code>SameSite</code> posé par le backend — JS ne le voit jamais, l’interceptor appelle <code>/refresh</code> et le cookie part tout seul. C’est le pattern BFF. Le <code>sessionStorage</code> est un compromis acceptable pour un lab, jamais l’URL, et une CSP stricte réduit la surface XSS à la source.</p>`,
    lesson: 'auth-jwt',
  },
  {
    id: 'auth-httponly', topic: 'auth', level: 1, type: 'mcq',
    question: 'Que garantit le flag HttpOnly sur un cookie ?',
    choices: [
      'Le cookie n’est envoyé qu’en HTTP, pas en HTTPS.',
      'Le cookie est inaccessible à JavaScript (document.cookie), ce qui empêche un script XSS de le voler.',
      'Le cookie n’est envoyé qu’aux requêtes same-site.',
      'Le cookie est chiffré.',
    ],
    answer: 1,
    explanation: `<p><code>HttpOnly</code> = XSS ne peut pas lire. <code>Secure</code> = HTTPS uniquement. <code>SameSite</code> = pas envoyé depuis un site tiers (CSRF). Le chiffrement du contenu, lui, est fait par ASP.NET (Data Protection) pour le ticket d’auth.</p>`,
    lesson: 'auth-cookie',
  },
  {
    id: 'auth-api-checklist', topic: 'auth', level: 3, type: 'open',
    question: 'Tu exposes une API publique. Donne ta check-list sécurité.',
    keyPoints: [
      { text: 'HTTPS partout, HSTS, redirection', keywords: ['https', 'hsts', 'tls'] },
      { text: 'Authentification adaptée (OIDC/JWT/API key) + autorisation par policies', keywords: ['auth', 'jwt', 'oidc', 'api key', 'policy'] },
      { text: 'Rate limiting (surtout login), tailles de payload limitées', keywords: ['rate', 'limit', 'throttl', 'taille', 'payload', 'brute'] },
      { text: 'Validation stricte des entrées, requêtes paramétrées (pas d’injection SQL)', keywords: ['valid', 'injection', 'paramétr', 'parametr', 'entrée', 'entree', 'input'] },
      { text: 'Erreurs sans stack trace (ProblemDetails), logs/audit avec traceId, pas de secrets dans le code', keywords: ['stack', 'problemdetails', 'log', 'audit', 'secret', 'env', 'vault'] },
      { text: 'CORS strict, headers de sécurité, dépendances auditées (dotnet list package --vulnerable)', keywords: ['cors', 'header', 'csp', 'dépendance', 'dependance', 'vulnerab', 'audit', 'npm audit'] },
    ],
    model: `<p>Transport : HTTPS seul, HSTS. Identité : un scheme adapté au client (OIDC pour les humains, API key ou client credentials pour les machines), et des policies plutôt que des <code>if role</code>. Abus : rate limiting partitionné par identité, plus strict sur le login, limites de taille de body. Entrées : validation systématique (FluentValidation), EF Core paramétré — jamais de SQL concaténé. Sorties : ProblemDetails sans stack trace, headers de sécurité, CORS restreint aux origines connues. Exploitation : secrets hors du code (env, Key Vault), logs corrélés par traceId, audit des actions sensibles, dépendances scannées en CI. Et des tests d’intégration qui vérifient que les 401/403 sont bien là.</p>`,
  },

  // ═══════════════════════════ ARCHITECTURE ═══════════════════════════
  {
    id: 'arch-vsa-vs-clean', topic: 'architecture', level: 2, type: 'open',
    question: 'Vertical Slice Architecture vs Clean Architecture : compare et dis quand tu choisis l’une ou l’autre.',
    keyPoints: [
      { text: 'Clean : couches concentriques, dépendances vers le domaine, abstractions (interfaces, repositories)', keywords: ['couche', 'domaine', 'domain', 'dépendance', 'dependance', 'interface', 'repository', 'abstraction', 'concentr'] },
      { text: 'VSA : découpage par feature, tout ce qui change ensemble vit ensemble, peu d’abstractions', keywords: ['feature', 'slice', 'tranche', 'ensemble', 'cas d’usage', 'cas d\'usage', 'dossier'] },
      { text: 'VSA : rapide à faire évoluer, moins de cérémonie ; risque de duplication → Shared quand nécessaire', keywords: ['duplication', 'shared', 'cérémonie', 'ceremonie', 'boilerplate', 'rapide', 'évolu', 'evolu'] },
      { text: 'Clean : utile quand le domaine est riche et partagé par beaucoup de cas d’usage, ou pour isoler l’infra', keywords: ['riche', 'complexe', 'partag', 'isol', 'infra', 'testab'] },
      { text: 'Les deux se combinent : slices + un domaine partagé quand il émerge', keywords: ['combin', 'mix', 'hybride', 'les deux', 'émerge', 'emerge'] },
    ],
    model: `<p>Clean Architecture organise le code en couches concentriques où tout dépend du domaine : beaucoup d’interfaces et d’abstractions, un domaine protégé, mais une feature simple traverse quatre projets. Vertical Slice retourne l’axe : un dossier par cas d’usage avec son endpoint, son handler, sa validation ; on ne crée une abstraction que quand deux slices en ont besoin. Je pars en slices par défaut — c’est plus rapide à lire et à faire évoluer — et je laisse émerger un domaine partagé (<code>Shared/</code>, puis un vrai modèle) quand les règles se répètent. Clean se justifie quand le domaine est vraiment riche et réutilisé par de nombreux cas d’usage, ou quand on doit pouvoir changer l’infrastructure fréquemment. Ce n’est pas exclusif : des slices avec un domaine propre au milieu, c’est courant.</p>`,
    diagram: 'slices', lesson: 'vertical-slice',
  },
  {
    id: 'arch-modular-monolith', topic: 'architecture', level: 3, type: 'open',
    question: 'Monolithe modulaire vs microservices : que recommandes-tu à une équipe de 6 qui démarre, et comment structures-tu le monolithe ?',
    keyPoints: [
      { text: 'Monolithe modulaire : un déploiement, des frontières explicites entre modules', keywords: ['monolithe', 'modul', 'déploiement', 'deploiement', 'frontière', 'frontiere', 'boundar'] },
      { text: 'Chaque module possède ses données (schéma/DbContext) et expose une PublicApi (interfaces + événements)', keywords: ['données', 'donnees', 'dbcontext', 'schéma', 'schema', 'publicapi', 'interface', 'événement', 'evenement', 'contrat'] },
      { text: 'Communication in-process : appel via interface, réaction via événements (outbox pour la fiabilité)', keywords: ['in-process', 'interface', 'événement', 'evenement', 'event', 'outbox'] },
      { text: 'Frontières garanties : projets séparés ou tests d’architecture', keywords: ['projet', 'assembly', 'test', 'archi', 'netarchtest', 'compil'] },
      { text: 'Microservices = coût réseau, cohérence, observabilité, déploiement ; extraire un module plus tard si besoin', keywords: ['réseau', 'reseau', 'cohéren', 'coheren', 'observab', 'coût', 'cout', 'extrai', 'plus tard', 'sortir'] },
    ],
    model: `<p>Pour six personnes qui démarrent : un monolithe modulaire, sans hésiter. Un seul déploiement, une seule base de code, mais des modules aux frontières explicites : chaque module possède ses tables (son <code>DbContext</code>), ses endpoints, et n’expose qu’une <em>PublicApi</em> minimale — quelques interfaces pour les appels synchrones et des événements pour les réactions. Les modules ne se touchent pas autrement, et cette règle est vérifiée par le compilateur (projets séparés) ou par des tests d’architecture. Les microservices apportent l’indépendance de déploiement et de scaling, mais au prix du réseau, de la cohérence des données, de l’observabilité distribuée et d’une complexité opérationnelle qu’une petite équipe paiera cher. Si un module doit un jour scaler seul, ses dépendances sont déjà des interfaces et des événements : on le sort sans réécrire le reste.</p>`,
    diagram: 'modules', lesson: 'modular-monolith',
  },
  {
    id: 'arch-outbox', topic: 'architecture', level: 2, type: 'mcq',
    question: 'À quoi sert le pattern Outbox ?',
    choices: [
      'À mettre en cache les réponses HTTP sortantes.',
      'À garantir qu’un événement est publié si et seulement si la transaction métier a été commitée : l’événement est écrit dans la même transaction (table outbox), puis dispatché par un processus séparé.',
      'À regrouper les emails sortants.',
      'À stocker les requêtes échouées pour rejeu manuel.',
    ],
    answer: 1,
    explanation: `<p>Sans outbox, deux échecs possibles : la commande est sauvée mais la publication plante (stock jamais décrémenté), ou l’événement part mais la transaction est rollbackée (stock décrémenté pour une commande inexistante). Écrire l’événement dans la même transaction que la commande, puis le relayer (job, CDC) avec retry et idempotence côté consommateur, résout les deux.</p>`,
    diagram: 'modules', lesson: 'modular-monolith',
  },
  {
    id: 'arch-choose-db', topic: 'architecture', level: 2, type: 'open',
    question: 'Comment choisis-tu une base de données pour un nouveau projet ?',
    keyPoints: [
      { text: 'Partir du modèle de données et des requêtes : relations, transactions, cohérence', keywords: ['modèle', 'modele', 'relation', 'requête', 'requete', 'transaction', 'cohéren', 'coheren', 'acid'] },
      { text: 'Postgres par défaut : relationnel, JSONB, full-text, extensions ; couvre 90 % des cas', keywords: ['postgres', 'relationnel', 'sql', 'défaut', 'defaut', 'jsonb'] },
      { text: 'NoSQL seulement pour un besoin précis : documents sans schéma stable, volume/écriture massifs, graphe, time series', keywords: ['nosql', 'document', 'mongo', 'graphe', 'time series', 'volume', 'écriture', 'ecriture', 'cassandra', 'dynamo'] },
      { text: 'Redis = cache/queue, pas la source de vérité ; recherche = Elastic/OpenSearch en plus', keywords: ['redis', 'cache', 'elastic', 'opensearch', 'recherche', 'search'] },
      { text: 'Critères opérationnels : compétences de l’équipe, managé ou non, coût, backup, migrations', keywords: ['équipe', 'equipe', 'compétence', 'competence', 'managé', 'manage', 'coût', 'cout', 'backup', 'ops', 'migration'] },
    ],
    model: `<p>Je pars des données et des accès : quelles entités, quelles relations, quelles requêtes, quel besoin de transactions et de cohérence. Pour l’immense majorité des applications métier, la réponse est Postgres : relationnel, transactions, JSONB quand il faut de la souplesse, full-text correct, écosystème et hébergement managé partout. Une base NoSQL se justifie sur un besoin identifié — documents vraiment sans schéma, volumes d’écriture massifs, graphe, séries temporelles — pas par mode. Redis vient <em>en plus</em> pour le cache et les files, jamais comme source de vérité ; un moteur de recherche dédié si la recherche est centrale. Et je pèse l’opérationnel : ce que l’équipe sait exploiter, le coût managé, les sauvegardes, les migrations.</p>`,
  },
  {
    id: 'arch-error-codes', topic: 'architecture', level: 1, type: 'mcq',
    question: 'Pourquoi une Error métier porte-t-elle un code stable (orders.insufficient_stock) en plus du message ?',
    choices: [
      'Pour la traduction automatique.',
      'Parce que le front et les tests s’appuient sur le code, jamais sur le texte : on peut reformuler le message sans rien casser.',
      'Parce que ProblemDetails l’exige.',
      'Pour le logging uniquement.',
    ],
    answer: 1,
    explanation: `<p>Un message est pour l’humain (et peut être traduit, reformulé) ; un code est un contrat pour les machines : <code>if (error.code === 'orders.insufficient_stock')</code> côté Angular, <code>Assert.Contains("orders.insufficient_stock", body)</code> côté tests.</p>`,
    lesson: 'vertical-slice',
  },
  {
    id: 'arch-notifications', topic: 'architecture', level: 3, type: 'open',
    question: 'Conçois un service de notifications (email/SMS/push) pour une plateforme SaaS. Quels composants, quels problèmes ?',
    keyPoints: [
      { text: 'Découplage asynchrone : les producteurs publient un événement/message dans une file (queue)', keywords: ['file', 'queue', 'asynchrone', 'message', 'événement', 'evenement', 'rabbit', 'service bus', 'kafka', 'découpl', 'decoupl'] },
      { text: 'Workers consommateurs avec retry/backoff et dead-letter queue', keywords: ['worker', 'retry', 'backoff', 'dead', 'dlq', 'réessai', 'reessai'] },
      { text: 'Idempotence : une clé par notification pour ne jamais envoyer deux fois', keywords: ['idempot', 'doublon', 'deux fois', 'clé', 'cle', 'dédupl', 'dedupl'] },
      { text: 'Templates + préférences utilisateur (canal, opt-out, langue) + rate limits des fournisseurs', keywords: ['template', 'préférence', 'preference', 'opt', 'langue', 'canal', 'fournisseur', 'provider', 'rate'] },
      { text: 'Observabilité : statut par notification, traceId, métriques d’échec', keywords: ['statut', 'status', 'trace', 'métrique', 'metrique', 'observab', 'log', 'monitor'] },
    ],
    model: `<p>Le cœur : ne jamais envoyer une notification dans la requête HTTP qui la déclenche. Les modules métier publient un message (« commande confirmée ») dans une file ; un service de notifications le consomme, résout les préférences de l’utilisateur (canaux, opt-out, langue), rend un template, et appelle le fournisseur (SendGrid, Twilio, FCM) via un adaptateur par canal. Chaque envoi porte une clé d’idempotence — un retry ne doit jamais doubler un SMS. Les échecs partent en retry avec backoff, puis en dead-letter queue pour analyse. Les fournisseurs ont des quotas : un rate limiter par fournisseur. Et chaque notification a un statut persisté (queued, sent, failed, delivered via webhook) corrélé par traceId, avec des métriques d’échec qui alertent.</p>`,
  },
];
